'use strict';

const cfg=window.DMO_CONFIG||{};
const sb=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const today=new Date(), initialMonth=`${today.getUTCFullYear()}-${String(today.getUTCMonth()+1).padStart(2,'0')}`;
let period=initialMonth, session=null, me=null, view='assign', state=emptyState(), busy=false;
let assignFilter={pending:false,responsible:''};

function emptyState(){return{responsibles:[],centers:[],people:[],versions:[],lines:[],confirmations:[],validations:[],hrValidations:[],users:[],events:[]}}
const monthDate=()=>period+'-01';
const monthEnd=()=>{const[y,m]=period.split('-').map(Number);return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)};
const periodLabel=()=>new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(period+'-01T00:00:00Z'));
const fmtDate=v=>v?new Date(v).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'}):'—';
const roleLabel=()=>({rrhh:'RRHH',responsable:'Responsable',administrador:'Administrador de costos'})[me?.role]||'Sin perfil';
const responsible=id=>state.responsibles.find(x=>x.id===id);
const center=id=>state.centers.find(x=>x.id===id);
const activeCenters=()=>state.centers.filter(c=>c.active);
const person=id=>state.people.find(x=>x.id===id);
const activeInMonth=p=>p.start_date<=monthEnd()&&(!p.end_date||p.end_date>=monthDate());
const activePeople=()=>state.people.filter(activeInMonth);
const canManagePeople=()=>['rrhh','administrador'].includes(me?.role);
const canAssign=p=>me?.role==='administrador'||(me?.role==='responsable'&&p.responsible_id===me.responsible_id);
function currentVersion(personId,date=monthEnd()){return state.versions.filter(v=>v.person_id===personId&&v.valid_from<=date&&(!v.valid_to||v.valid_to>=date)).sort((a,b)=>a.valid_from.localeCompare(b.valid_from)).at(-1)}
const usesInactiveCenter=id=>allocation(id).some(a=>center(a.center_id)&&!center(a.center_id).active);
function allocation(personId){const v=currentVersion(personId);return v?state.lines.filter(x=>x.version_id===v.id).map(x=>({...x,version:v})):[]}
const total=id=>allocation(id).reduce((s,x)=>s+Number(x.pct),0);
const complete=id=>allocation(id).length>0&&Math.abs(total(id)-100)<.001;
const ownsCenter=(centerId,rid=me?.responsible_id)=>center(centerId)?.responsible_id===rid;
// Una confirmación se mantiene en los meses siguientes mientras el porcentaje de ese centro no cambie.
const confirmation=(personId,centerId)=>{const v=currentVersion(personId);if(!v)return;const pctOf=vid=>state.lines.find(l=>l.version_id===vid&&l.center_id===centerId)?.pct,cur=pctOf(v.id),same=x=>x!=null&&Math.abs(Number(x)-Number(cur))<1e-6;if(cur==null)return;return state.confirmations.filter(x=>x.period<=monthDate()&&x.person_id===personId&&x.center_id===centerId).sort((a,b)=>b.period.localeCompare(a.period)).find(x=>{const cv=state.versions.find(y=>y.id===x.version_id);return cv&&cv.valid_from<=v.valid_from&&same(pctOf(cv.id))&&state.versions.filter(y=>y.person_id===personId&&y.valid_from>cv.valid_from&&y.valid_from<=v.valid_from).every(y=>same(pctOf(y.id)))})};
const confirmedBadge=c=>badge(c.period===monthDate()?'Confirmado':`Confirmado en ${new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(c.period+'T00:00:00Z'))}`,'ok');
function missingShared(personId){const p=person(personId);return allocation(personId).filter(x=>center(x.center_id)?.responsible_id&&center(x.center_id).responsible_id!==p.responsible_id&&!confirmation(personId,x.center_id))}
function receivedShared(){if(me?.role!=='responsable')return[];return activePeople().flatMap(p=>allocation(p.id).filter(a=>p.responsible_id!==me.responsible_id&&ownsCenter(a.center_id)).map(a=>({p,a,c:center(a.center_id)})))}
const validated=rid=>state.validations.some(x=>x.period===monthDate()&&x.responsible_id===rid);
const hrValidated=()=>state.hrValidations.some(x=>x.period===monthDate());
function myPrimary(){return activePeople().filter(p=>p.responsible_id===me?.responsible_id)}
function responsibleReady(rid){const mine=activePeople().filter(p=>p.responsible_id===rid);const received=activePeople().flatMap(p=>allocation(p.id).filter(a=>p.responsible_id!==rid&&center(a.center_id)?.responsible_id===rid).map(a=>({p,a})));return(mine.length>0||received.length>0)&&mine.every(p=>complete(p.id)&&missingShared(p.id).length===0)&&received.every(x=>confirmation(x.p.id,x.a.center_id))}
const personIssues=p=>{const out=[];if(!allocation(p.id).length)out.push('Sin asignar');else if(!complete(p.id))out.push(`Suma ${total(p.id).toFixed(2)}%`);if(usesInactiveCenter(p.id))out.push('Tiene un centro dado de baja');return out};
const isPending=p=>personIssues(p).length>0||missingShared(p.id).length>0;
function pendingDetail(rid){const r=responsible(rid),mine=activePeople().filter(p=>p.responsible_id===rid),pct=a=>`${Number(a.pct).toFixed(2)}%`;const toComplete=mine.map(p=>({p,issues:personIssues(p)})).filter(x=>x.issues.length);const toConfirm=activePeople().filter(p=>p.responsible_id!==rid).flatMap(p=>allocation(p.id).filter(a=>center(a.center_id)?.responsible_id===rid&&!confirmation(p.id,a.center_id)).map(a=>({p,a})));const waiting=mine.flatMap(p=>missingShared(p.id).map(a=>({p,a})));const parts=[];if(toComplete.length)parts.push(`<h4>Asignaciones por completar</h4><ul>${toComplete.map(x=>`<li>${esc(x.p.name)} (${esc(x.p.id)}): ${esc(x.issues.join(' · '))}</li>`).join('')}</ul>`);if(toConfirm.length)parts.push(`<h4>Tiene que confirmar</h4><ul>${toConfirm.map(x=>`<li>${esc(x.p.name)} · ${esc(center(x.a.center_id).name)} ${pct(x.a)} <span class="small">(lo asignó ${esc(responsible(x.p.responsible_id)?.name||'—')})</span></li>`).join('')}</ul>`);if(waiting.length)parts.push(`<h4>Esperando que confirme otro responsable</h4><ul>${waiting.map(x=>`<li>${esc(x.p.name)} · ${esc(center(x.a.center_id).name)} ${pct(x.a)} <span class="small">(confirma ${esc(responsible(center(x.a.center_id).responsible_id)?.name||'—')})</span></li>`).join('')}</ul>`);if(!parts.length&&!validated(rid))parts.push('<p>Tiene todo completo: sólo falta que toque <b>Validar todo el mes</b>.</p>');if(!parts.length)return'';return`<details class="pending-detail"><summary>Ver qué falta</summary>${r?.email?`<p>Correo: <a href="mailto:${esc(r.email)}">${esc(r.email)}</a></p>`:''}${parts.join('')}</details>`}

function toast(text,error=false){const n=$('#toast');n.textContent=text;n.style.background=error?'#8f343b':'';n.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>n.hidden=true,4300)}
function badge(text,type=''){return`<span class="badge ${type}">${esc(text)}</span>`}
function initials(name){return String(name).split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function head(title,lead,actions=''){return`<div class="heading"><div><h1>${esc(title)}</h1><p class="lead">${esc(lead)}</p></div><div class="actions">${actions}</div></div>`}
function modal(title,body,foot=''){const d=$('#modal');d.innerHTML=`<div class="modalhead"><h2>${esc(title)}</h2><button id="modalClose" class="close" aria-label="Cerrar">×</button></div><div class="modalbody">${body}</div>${foot?`<div class="modalfoot">${foot}</div>`:''}`;$('#modalClose').onclick=()=>d.close();d.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>d.close());d.showModal()}
async function run(promise){if(busy)throw new Error('Hay otra operación en curso.');busy=true;try{const{data,error}=await promise;if(error)throw error;return data}finally{busy=false}}
async function audit(type,description){const{error}=await sb.from('audit_events').insert({actor_email:session.user.email.toLowerCase(),event_type:type,description});if(error)console.warn(error.message)}

async function boot(){
  if(!sb){showLoginError('Falta la configuración de Supabase.');return}
  $('#loginForm').onsubmit=sendLogin;$('#logout').onclick=()=>sb.auth.signOut();$('#myPassword').onclick=openMyPassword;$('#periodFilter').onchange=e=>{period=e.target.value;render()};
  sb.auth.onAuthStateChange((_event,newSession)=>setTimeout(()=>acceptSession(newSession),0));
  const{data}=await sb.auth.getSession();await acceptSession(data.session);
}
async function sendLogin(e){e.preventDefault();const email=$('#loginEmail').value.trim().toLowerCase(),password=$('#loginPassword').value,box=$('#loginMessage');box.className='login-message';box.textContent='Ingresando…';const{error}=await sb.auth.signInWithPassword({email,password});if(error){box.classList.add('error');box.textContent=/invalid login credentials/i.test(error.message)?'Correo o contraseña incorrectos.':error.message;return}$('#loginPassword').value='';box.textContent=''}
function showLoginError(text){$('#login').hidden=false;$('#secureApp').hidden=true;const box=$('#loginMessage');box.textContent=text;box.className='login-message error'}
async function acceptSession(next){session=next;if(!session){me=null;state=emptyState();$('#login').hidden=false;$('#secureApp').hidden=true;return}const email=session.user.email.toLowerCase();const{data,error}=await sb.from('app_users').select('*').eq('email',email).eq('active',true).maybeSingle();if(error||!data){await sb.auth.signOut();showLoginError('Tu usuario no está habilitado en la aplicación. Pedile acceso a RRHH o al administrador.');return}me=data;$('#login').hidden=true;$('#secureApp').hidden=false;view=me.role==='responsable'?'assign':'roster';await loadData()}
// Supabase entrega como máximo 1000 filas por consulta: se piden páginas hasta completar el total.
async function fetchAll(build){const out=[];for(;;){const{data,error,count}=await build().range(out.length,out.length+999);if(error)return{error};out.push(...data);if(!data.length||(count!=null?out.length>=count:data.length<1000))return{data:out}}}
async function loadData(){
  $('#app').innerHTML='<div class="loading">Cargando información…</div>';
  const page=(table,order,filter=q=>q)=>fetchAll(()=>order.reduce((q,c)=>q.order(c),filter(sb.from(table).select('*',{count:'exact'}))));
  const queries=[page('responsibles',['name','id'],q=>q.eq('active',true)),page('centers',['sort_order','id']),page('people',['name','id']),page('assignment_versions',['valid_from','id']),page('assignment_lines',['id']),page('shared_confirmations',['period','person_id','center_id']),page('monthly_validations',['period','responsible_id']),page('hr_validations',['period']),sb.from('audit_events').select('*').order('created_at',{ascending:false}).limit(200)];
  if(canManagePeople())queries.push(page('app_users',['display_name','email']));
  const results=await Promise.all(queries);const failed=results.find(x=>x.error);if(failed){showFatal(failed.error.message);return}
  [state.responsibles,state.centers,state.people,state.versions,state.lines,state.confirmations,state.validations,state.hrValidations,state.events,state.users]=results.map(x=>x.data||[]);render();
}
function showFatal(message){$('#app').innerHTML=`<div class="notice danger"><b>No se pudo cargar la aplicación.</b><br>${esc(message)}<br><br>Verificá que se haya ejecutado <code>supabase/setup.sql</code>.</div>`}

const NAV={rrhh:[['roster','▤','Nómina'],['centers','⌂','Centros'],['users','＠','Accesos'],['assign','％','Asignaciones'],['validation','✓','Cierre mensual'],['history','◷','Historial']],responsable:[['assign','％','Mi personal'],['validation','✓','Validación mensual']],administrador:[['roster','▤','Nómina'],['centers','⌂','Centros'],['users','＠','Accesos'],['assign','％','Asignaciones'],['validation','✓','Cierre mensual'],['export','⇩','Exportar'],['history','◷','Historial']]};
function render(){if(me.must_change_password){renderForcedPassword();return}const nav=NAV[me.role];if(!nav.some(x=>x[0]===view))view=nav[0][0];$('#nav').innerHTML=nav.map(x=>`<button class="navbtn ${view===x[0]?'active':''}" data-view="${x[0]}"><i>${x[1]}</i>${x[2]}</button>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#periodFilter').value=period;$('#periodAside').textContent=periodLabel();$('#rolePill').textContent=roleLabel();$('#signedUser').textContent=session.user.email;const fn={roster:rosterView,centers:centersView,users:usersView,assign:assignView,validation:validationView,export:exportView,history:historyView}[view];$('#app').innerHTML=fn();bind()}
function passwordFields(forced){return`${forced?'':'<label class="field">Contraseña actual<input id="pwdCurrent" type="password" autocomplete="current-password"></label>'}<label class="field">Nueva contraseña<input id="pwdNew" type="password" autocomplete="new-password"></label><label class="field">Repetir nueva contraseña<input id="pwdRepeat" type="password" autocomplete="new-password"></label><p class="small">Mínimo 8 caracteres.</p><div id="pwdError" class="error"></div>`}
async function saveOwnPassword(forced){const next=$('#pwdNew').value;if(next.length<8){$('#pwdError').textContent='La contraseña debe tener al menos 8 caracteres.';return false}if(next!==$('#pwdRepeat').value){$('#pwdError').textContent='Las contraseñas no coinciden.';return false}try{await run(sb.rpc('change_my_password',{current_password:forced?'':$('#pwdCurrent').value,new_password:next}));me.must_change_password=false;await audit('access','Cambio de contraseña propia');return true}catch(e){$('#pwdError').textContent=e.message;return false}}
function renderForcedPassword(){$('#nav').innerHTML='';$('#periodAside').textContent=periodLabel();$('#rolePill').textContent=roleLabel();$('#signedUser').textContent=session.user.email;$('#app').innerHTML=head('Elegí tu contraseña','Antes de continuar, reemplazá la contraseña inicial por una que sólo sepas vos.')+`<section class="panel" style="max-width:520px"><div class="panelbody">${passwordFields(true)}<button class="btn primary" id="saveForcedPwd">Guardar contraseña</button></div></section>`;$('#saveForcedPwd').onclick=async()=>{if(await saveOwnPassword(true)){toast('Contraseña guardada.');render()}}}
function openMyPassword(){if(me?.must_change_password)return;modal('Cambiar mi contraseña',passwordFields(false),`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveMyPwd">Guardar</button>`);$('#saveMyPwd').onclick=async()=>{if(await saveOwnPassword(false)){$('#modal').close();toast('Contraseña actualizada.')}}}
function randomPassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789',v=crypto.getRandomValues(new Uint32Array(10));return[...v].map(x=>chars[x%chars.length]).join('')}
const canSetPassword=u=>me?.role==='administrador'||(me?.role==='rrhh'&&u.role!=='administrador');
const initialPasswordField=()=>`<label class="field">Contraseña inicial<span style="display:flex;gap:8px;margin-top:6px"><input id="initPwd" type="text" autocomplete="off" style="flex:1"><button type="button" class="btn" id="genPwd">Generar</button></span></label><p class="small">Mínimo 8 caracteres. Pasásela a la persona por un medio privado: al ingresar, la aplicación le va a pedir que la cambie.</p>`;
function bindInitialPassword(){$('#genPwd').onclick=()=>{$('#initPwd').value=randomPassword()}}
function readInitialPassword(){const pwd=$('#initPwd').value;if(pwd.length<8){$('#formError').textContent='La contraseña inicial debe tener al menos 8 caracteres.';return null}return pwd}
function openSetPassword(email){const u=state.users.find(x=>x.email===email);if(!u||!canSetPassword(u))return;modal('Contraseña de acceso',`<p><b>${esc(u.display_name)}</b> · ${esc(u.email)}</p>${initialPasswordField()}${u.password_set_at?'<p class="small">Si la persona tenía una sesión abierta, se va a cerrar.</p>':''}<div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveInitPwd">Guardar</button>`);bindInitialPassword();$('#saveInitPwd').onclick=async()=>{const pwd=readInitialPassword();if(!pwd)return;try{await run(sb.rpc('set_user_password',{target_email:email,new_password:pwd}));$('#modal').close();await loadData();toast('Contraseña guardada.')}catch(e){$('#formError').textContent=e.message}}}

function rosterView(){const list=activePeople();return head('Nómina de personal',`RRHH mantiene altas, bajas y responsable principal. Período: ${periodLabel()}.`,`<a class="btn" href="assets/Plantilla_Importacion_Personal_DMO.xlsx" download>Descargar plantilla</a><button class="btn" id="importRoster" ${state.people.length?'disabled':''}>Importación inicial</button>${me.role==='administrador'&&state.people.length?'<button class="btn danger" id="clearTest">Vaciar datos de prueba</button>':''}<button class="btn primary" id="newHire">＋ Nuevo ingreso</button>`)+`<div class="cards"><div class="card"><span>Personas del período</span><strong>${list.length}</strong><small>Con vigencia en el mes</small></div><div class="card"><span>Activas al cierre</span><strong>${list.filter(p=>!p.end_date||p.end_date>=monthEnd()).length}</strong><small>Al ${monthEnd().split('-').reverse().join('/')}</small></div><div class="card"><span>Altas del mes</span><strong>${state.people.filter(p=>p.start_date.startsWith(period)).length}</strong></div><div class="card"><span>Bajas del mes</span><strong>${state.people.filter(p=>p.end_date?.startsWith(period)).length}</strong></div></div><section class="panel"><div class="panelhead"><div><h2>Personal vigente</h2><p>Las bajas conservan todo el historial.</p></div>${badge(hrValidated()?'Nómina validada':'Falta validación RRHH',hrValidated()?'ok':'pending')}</div><div class="tablewrap"><table><thead><tr><th>Legajo y nombre</th><th>Vigencia</th><th>Responsable principal</th><th>Asignación</th><th>Acciones</th></tr></thead><tbody>${list.map(p=>`<tr><td><b>${esc(p.name)}</b><br><span class="small">${esc(p.id)}</span></td><td>Alta: ${p.start_date.split('-').reverse().join('/')}<br>${p.end_date?'Baja: '+p.end_date.split('-').reverse().join('/'):badge('Activa','ok')}</td><td>${esc(responsible(p.responsible_id)?.name||'Sin responsable')}</td><td>${complete(p.id)?badge('100%','ok'):badge(`${Number(total(p.id)).toFixed(2)}%`,'bad')}</td><td><div class="actions"><button class="btn" data-owner="${esc(p.id)}">Cambiar responsable</button><button class="btn" data-end="${esc(p.id)}">${p.end_date?'Modificar baja':'Registrar baja'}</button></div></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay personas cargadas.</td></tr>'}</tbody></table></div></section>`}

function allocationHtml(id){const rows=allocation(id);if(!rows.length)return badge('Sin asignar','bad');return`<div class="allocation">${rows.map(a=>`<div><small>${esc(center(a.center_id)?.name||a.center_id)}${center(a.center_id)&&!center(a.center_id).active?' (de baja)':''}</small><b>${Number(a.pct).toFixed(Number(a.pct)%1?2:0)}%</b></div>`).join('')}<div class="bar">${rows.map(a=>`<i style="width:${Number(a.pct)}%"></i>`).join('')}</div></div>`}
function assignView(){let list=me.role==='responsable'?myPrimary():activePeople();const all=list.length;if(me.role!=='responsable'&&assignFilter.responsible)list=list.filter(p=>p.responsible_id===assignFilter.responsible);if(assignFilter.pending)list=list.filter(isPending);return head(me.role==='responsable'?'Mi personal':'Asignaciones','La persona responsable principal carga el reparto completo; el responsable receptor confirma su parte.')+`<section class="panel"><div class="panelhead"><div><h2>${me.role==='responsable'?esc(responsible(me.responsible_id)?.name||'Responsable'):'Todas las personas'}</h2><p>Cada distribución debe sumar exactamente 100%.${list.length!==all?` Mostrando ${list.length} de ${all}.`:''}</p></div><div class="filters">${me.role!=='responsable'?`<select id="filterResponsible"><option value="">Todos los responsables</option>${state.responsibles.map(r=>`<option value="${r.id}" ${assignFilter.responsible===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select>`:''}<select id="filterPending"><option value="">Todas las personas</option><option value="1" ${assignFilter.pending?'selected':''}>Solo pendientes</option></select></div></div><div class="tablewrap"><table><thead><tr><th>Persona</th><th>Distribución</th><th>Estado</th><th>Responsable</th><th>Acción</th></tr></thead><tbody>${list.map(p=>`<tr><td><div class="person"><span class="circle">${initials(p.name)}</span><div class="name"><b>${esc(p.name)}</b><small>${esc(p.id)}</small></div></div></td><td>${allocationHtml(p.id)}</td><td>${usesInactiveCenter(p.id)?badge('Centro dado de baja: reasignar','bad'):!complete(p.id)?badge('Falta completar','bad'):missingShared(p.id).length?badge(`${missingShared(p.id).length} confirmación pendiente`,'pending'):badge('Lista','ok')}</td><td>${esc(responsible(p.responsible_id)?.name||'—')}</td><td>${canAssign(p)?`<button class="btn" data-assign="${esc(p.id)}">Editar asignación</button>`:`<button class="btn" data-detail="${esc(p.id)}">Ver</button>`}</td></tr>`).join('')||`<tr><td colspan="5" class="empty">${list.length!==all?'No hay personas con este filtro.':'No hay personas para mostrar.'}</td></tr>`}</tbody></table></div></section>${me.role==='responsable'?sharedPanel():''}`}
function sharedPanel(){const rows=receivedShared();return`<section class="panel"><div class="panelhead"><div><h2>Dedicaciones recibidas</h2><p>Confirmá sólo el porcentaje que corresponde a tus centros.</p></div></div>${rows.map(x=>`<div class="listrow"><div><b>${esc(x.p.name)}</b><p>${esc(x.c.name)} · ${Number(x.a.pct).toFixed(2)}%</p></div>${confirmation(x.p.id,x.c.id)?confirmedBadge(confirmation(x.p.id,x.c.id)):`<button class="btn primary" data-confirm="${esc(x.p.id)}|${esc(x.c.id)}">Confirmar</button>`}</div>`).join('')||'<div class="empty">No recibiste dedicaciones de otros responsables.</div>'}</section>`}

function centersView(){const active=activeCenters(),inactive=state.centers.filter(c=>!c.active),manage=canManagePeople();return head('Centros','El catálogo se importa en forma autenticada y queda almacenado únicamente en Supabase.',manage?'<button class="btn" id="newCenter">＋ Centro</button><button class="btn primary" id="importCenters">Importar catálogo</button>':'')+`<section class="panel"><div class="panelhead"><div><h2>${active.length} centros vigentes</h2><p>El responsable del centro confirma dedicaciones recibidas.</p></div></div><div class="tablewrap"><table><thead><tr><th>Código</th><th>Unidad</th><th>Centro</th><th>Tipo</th><th>Responsable</th>${manage?'<th></th>':''}</tr></thead><tbody>${active.map(c=>`<tr><td class="${c.provisional?'provisional':''}">${esc(c.code)}${c.provisional?' · pendiente':''}</td><td>${esc(c.unit)}</td><td><b>${esc(c.name)}</b></td><td>${badge(c.type,c.type==='Beneficio'?'ok':'')}</td><td><select data-center-owner="${esc(c.id)}"><option value="">Sin responsable</option>${state.responsibles.map(r=>`<option value="${r.id}" ${c.responsible_id===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></td>${manage?`<td><button class="btn danger" data-center-off="${esc(c.id)}">Dar de baja</button></td>`:''}</tr>`).join('')||`<tr><td colspan="${manage?6:5}" class="empty">Todavía no se importó el catálogo de centros.</td></tr>`}</tbody></table></div></section>${inactive.length?`<section class="panel"><div class="panelhead"><div><h2>${inactive.length} ${inactive.length===1?'centro dado':'centros dados'} de baja</h2><p>No se pueden elegir en nuevas asignaciones; los meses anteriores los conservan.</p></div></div><div class="tablewrap"><table><thead><tr><th>Código</th><th>Unidad</th><th>Centro</th><th>Tipo</th>${manage?'<th></th>':''}</tr></thead><tbody>${inactive.map(c=>`<tr><td class="muted">${esc(c.code)}</td><td class="muted">${esc(c.unit)}</td><td class="muted">${esc(c.name)}</td><td>${badge(c.type)}</td>${manage?`<td><button class="btn" data-center-on="${esc(c.id)}">Reactivar</button></td>`:''}</tr>`).join('')}</tbody></table></div></section>`:''}`}

function usersView(){return head('Usuarios y perfiles','Cada usuario ingresa con su correo y contraseña; su perfil determina lo que puede ver y hacer.',`<button class="btn" id="newResponsible">＋ Responsable</button><button class="btn primary" id="newUser">＋ Usuario</button>`)+`<div class="notice"><b>No se repiten correos en la nómina.</b> Los responsables se mantienen en este maestro y se vinculan con cada persona.</div><section class="panel"><div class="panelhead"><h2>Accesos habilitados</h2></div><div class="tablewrap"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Perfil</th><th>Estado</th><th>Contraseña</th></tr></thead><tbody>${state.users.map(u=>`<tr><td><b>${esc(u.display_name)}</b></td><td>${esc(u.email)}</td><td>${badge(roleName(u.role))}</td><td>${u.active?badge('Activo','ok'):badge('Bloqueado','bad')}</td><td>${u.password_set_at?badge(u.must_change_password?'Inicial':'Asignada','ok'):badge('Pendiente','pending')} ${canSetPassword(u)?`<button class="btn link" data-password="${esc(u.email)}">${u.password_set_at?'Restablecer':'Asignar'}</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay usuarios visibles.</td></tr>'}</tbody></table></div></section><section class="panel"><div class="panelhead"><h2>Maestro de responsables</h2></div><div class="tablewrap"><table><thead><tr><th>Responsable</th><th>Correo</th><th>Personas principales</th><th>Centros</th></tr></thead><tbody>${state.responsibles.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.email)}</td><td>${state.people.filter(p=>p.responsible_id===r.id).length}</td><td>${activeCenters().filter(c=>c.responsible_id===r.id).length}</td></tr>`).join('')}</tbody></table></div></section>`}
const roleName=r=>({rrhh:'RRHH',responsable:'Responsable',administrador:'Administrador'})[r]||r;

function validationView(){
  const ids=new Set(activePeople().map(p=>p.responsible_id));activePeople().forEach(p=>allocation(p.id).forEach(a=>{if(center(a.center_id)?.responsible_id)ids.add(center(a.center_id).responsible_id)}));const reps=[...ids].map(responsible).filter(Boolean);
  if(me.role==='responsable'){const ready=responsibleReady(me.responsible_id);return head('Validación mensual',`Confirmación de ${periodLabel()}.`)+`<section class="panel"><div class="panelbody"><div class="summary"><div><h2>${validated(me.responsible_id)?'Período validado':'Revisión pendiente'}</h2><p>${ready?'Todas las asignaciones y confirmaciones están completas.':'Hay casos pendientes de completar o confirmar.'}</p></div>${validated(me.responsible_id)?badge('Validado','ok'):`<button class="btn primary" id="validateResponsible" ${ready?'':'disabled'}>Validar todo el mes</button>`}</div></div></section>`}
  return head('Cierre mensual',`Seguimiento por excepción de ${periodLabel()}.`)+`<div class="cards"><div class="card"><span>Personas</span><strong>${activePeople().length}</strong></div><div class="card"><span>Asignación incompleta</span><strong>${activePeople().filter(p=>!complete(p.id)).length}</strong></div><div class="card"><span>Confirmaciones pendientes</span><strong>${activePeople().reduce((s,p)=>s+missingShared(p.id).length,0)}</strong></div><div class="card"><span>Responsables validados</span><strong>${reps.filter(r=>validated(r.id)).length}/${reps.length}</strong></div></div><section class="panel"><div class="panelhead"><div><h2>Estado por responsable</h2><p>Sólo requieren intervención los casos marcados.</p></div>${canManagePeople()&&!hrValidated()?'<button class="btn primary" id="validateHr">Validar nómina RRHH</button>':badge('Nómina RRHH validada','ok')}</div>${reps.sort((a,b)=>(validated(a.id)&&responsibleReady(a.id))-(validated(b.id)&&responsibleReady(b.id))||a.name.localeCompare(b.name)).map(r=>`<div class="listrow"><div class="grow"><b>${esc(r.name)}</b><p>${state.people.filter(p=>p.responsible_id===r.id&&activeInMonth(p)).length} personas principales</p>${pendingDetail(r.id)}</div><div class="statusline">${responsibleReady(r.id)?badge('Sin pendientes','ok'):badge('Con pendientes','bad')}${validated(r.id)?badge('Validado','ok'):badge('Falta click','pending')}</div></div>`).join('')||'<div class="empty">Sin responsables para el período.</div>'}</section>`
}

function exportProblems(){const out=[];const people=activePeople();if(!people.length)out.push('No hay personas vigentes.');const incomplete=people.filter(p=>!complete(p.id));if(incomplete.length)out.push(`${incomplete.length} personas no suman 100%.`);const shared=people.reduce((s,p)=>s+missingShared(p.id).length,0);if(shared)out.push(`${shared} dedicaciones compartidas esperan confirmación.`);const ids=new Set(people.map(p=>p.responsible_id));people.forEach(p=>allocation(p.id).forEach(a=>{if(center(a.center_id)?.responsible_id)ids.add(center(a.center_id).responsible_id)}));const pending=[...ids].filter(id=>!validated(id));if(pending.length)out.push(`${pending.length} responsables todavía no validaron.`);if(!hrValidated())out.push('RRHH todavía no validó la nómina.');if(people.flatMap(p=>allocation(p.id)).some(a=>center(a.center_id)?.provisional))out.push('Hay centros con código provisional.');return out}
function exportView(){const problems=exportProblems();return head('Exportar asignaciones',`Salida del período ${periodLabel()}.`)+`<section class="panel"><div class="exportbox">${problems.length?`<div class="notice danger"><b>La exportación está bloqueada.</b><ul>${problems.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'<div class="notice"><b>Todos los controles están completos.</b><br>El archivo está listo para el modelo de costos.</div>'}<button class="btn primary" id="downloadOutput" ${problems.length?'disabled':''}>Descargar Excel</button></div></section>`}
function historyView(){return head('Historial','Trazabilidad de cambios realizados en la aplicación.')+`<section class="panel"><div class="panelhead"><h2>Actividad reciente</h2></div>${state.events.map(e=>`<div class="listrow"><div><span class="small">${esc(fmtDate(e.created_at))} · ${esc(e.actor_email)}</span><p style="color:var(--ink)">${esc(e.description)}</p></div></div>`).join('')||'<div class="empty">Todavía no hay actividad.</div>'}</section>`}

function bind(){
  $('#newHire')&&($('#newHire').onclick=openNewHire);$('#importRoster')&&($('#importRoster').onclick=openImport);$('#importCenters')&&($('#importCenters').onclick=openImportCenters);$('#newCenter')&&($('#newCenter').onclick=openNewCenter);document.querySelectorAll('[data-center-off]').forEach(b=>b.onclick=()=>openCenterOff(b.dataset.centerOff));document.querySelectorAll('[data-center-on]').forEach(b=>b.onclick=()=>setCenterActive(b.dataset.centerOn,true));$('#clearTest')&&($('#clearTest').onclick=openClearTest);$('#newResponsible')&&($('#newResponsible').onclick=openNewResponsible);$('#newUser')&&($('#newUser').onclick=openNewUser);document.querySelectorAll('[data-password]').forEach(b=>b.onclick=()=>openSetPassword(b.dataset.password));
  document.querySelectorAll('[data-owner]').forEach(b=>b.onclick=()=>openOwner(b.dataset.owner));document.querySelectorAll('[data-end]').forEach(b=>b.onclick=()=>openEnd(b.dataset.end));document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>openAssignment(b.dataset.assign));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>confirmShared(b.dataset.confirm));document.querySelectorAll('[data-center-owner]').forEach(s=>s.onchange=()=>saveCenterOwner(s.dataset.centerOwner,s.value));
  $('#validateResponsible')&&($('#validateResponsible').onclick=validateResponsible);$('#filterResponsible')&&($('#filterResponsible').onchange=e=>{assignFilter.responsible=e.target.value;render()});$('#filterPending')&&($('#filterPending').onchange=e=>{assignFilter.pending=!!e.target.value;render()});$('#validateHr')&&($('#validateHr').onclick=validateHr);$('#downloadOutput')&&($('#downloadOutput').onclick=downloadOutput);
}

function openNewHire(){
  if(!state.responsibles.length){toast('Primero cargá al menos un responsable.',true);return}
  modal('Registrar nuevo ingreso',`<div class="split"><label class="field">Legajo<input id="hireId"></label><label class="field">Fecha de alta<input id="hireDate" type="date" value="${monthDate()}"></label></div><label class="field">Apellido y nombre<input id="hireName"></label><label class="field">Responsable principal<select id="hireResp">${state.responsibles.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></label><div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveHire">Registrar alta</button>`);
  $('#saveHire').onclick=async()=>{const row={id:$('#hireId').value.trim(),name:$('#hireName').value.trim(),start_date:$('#hireDate').value,responsible_id:$('#hireResp').value};if(!row.id||!row.name||!row.start_date){$('#formError').textContent='Completá todos los datos.';return}try{await run(sb.from('people').insert(row));await run(sb.from('responsible_history').insert({person_id:row.id,valid_from:row.start_date,responsible_id:row.responsible_id,created_by:session.user.email}));await audit('hire',`Alta de ${row.name} (${row.id}) desde ${row.start_date}`);$('#modal').close();await loadData();toast('Alta registrada. Quedó pendiente la asignación.')}catch(e){$('#formError').textContent=e.message}}
}
function openEnd(id){const p=person(id);modal('Registrar o modificar baja',`<p><b>${esc(p.name)}</b> · ${esc(p.id)}</p><label class="field">Último día activo<input id="endDate" type="date" min="${p.start_date}" value="${p.end_date||monthEnd()}"></label><label class="field">Motivo u observación<input id="endReason"></label><div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveEnd">Guardar</button>`);$('#saveEnd').onclick=async()=>{const date=$('#endDate').value;if(!date||date<p.start_date){$('#formError').textContent='Revisá la fecha de baja.';return}try{await run(sb.from('people').update({end_date:date,updated_at:new Date().toISOString()}).eq('id',id));await audit('termination',`Baja de ${p.name} al ${date}${$('#endReason').value.trim()?': '+$('#endReason').value.trim():''}`);$('#modal').close();await loadData();toast('Baja registrada; el historial se conserva.')}catch(e){$('#formError').textContent=e.message}}}
function openOwner(id){const p=person(id);modal('Cambiar responsable principal',`<p><b>${esc(p.name)}</b> · ${esc(p.id)}</p><div class="split"><label class="field">Nuevo responsable<select id="ownerResp">${state.responsibles.map(r=>`<option value="${r.id}" ${r.id===p.responsible_id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><label class="field">Vigente desde<input id="ownerDate" type="date" min="${p.start_date}" value="${monthDate()}"></label></div><label class="field">Motivo<input id="ownerReason" placeholder="Ej.: transferencia de sector"></label><div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveOwner">Guardar</button>`);$('#saveOwner').onclick=async()=>{const rid=$('#ownerResp').value,date=$('#ownerDate').value;try{await run(sb.from('people').update({responsible_id:rid,updated_at:new Date().toISOString()}).eq('id',id));await run(sb.from('responsible_history').upsert({person_id:id,valid_from:date,responsible_id:rid,reason:$('#ownerReason').value.trim()||null,created_by:session.user.email},{onConflict:'person_id,valid_from'}));await audit('responsible_change',`Cambio de responsable de ${p.name} desde ${date}`);$('#modal').close();await loadData();toast('Responsable actualizado.')}catch(e){$('#formError').textContent=e.message}}}

function openAssignment(id){
  const p=person(id),existing=allocation(id),ownCount=state.centers.filter(c=>c.active&&c.responsible_id&&c.responsible_id===p.responsible_id).length;let showAll=!ownCount;const rows=existing.length?existing.map(x=>({center_id:x.center_id,pct:Number(x.pct)})):[{center_id:'',pct:100}];
  modal(`Asignar a ${p.name}`,`<label class="field">Vigente desde<input id="assignmentDate" type="date" value="${monthDate()}" min="${p.start_date}" ${p.end_date?`max="${p.end_date}"`:''}></label><div id="allocationRows"></div>${ownCount?`<label class="showall"><input type="checkbox" id="showAllCenters"><span>Mostrar también centros de otros responsables<small>Esa parte quedará pendiente hasta que el responsable del centro la confirme.</small></span></label>`:''}<button class="btn" id="addLine">＋ Agregar centro</button><div id="allocationTotal"></div><div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveAssignment">Guardar asignación</button>`);
  const paintTotal=()=>{const sum=rows.reduce((s,r)=>s+Number(r.pct||0),0);$('#allocationTotal').innerHTML=`<div class="total ${Math.abs(sum-100)<.001?'ok':'bad'}"><span>Total</span><b>${sum.toFixed(2)}%</b></div>`};
  const paint=()=>{$('#allocationRows').innerHTML=rows.map((r,i)=>`<div class="allocrow"><select data-line-center="${i}">${centerOptions(r.center_id,p.responsible_id,showAll)}</select><input data-line-pct="${i}" type="number" min="0.01" max="100" step="0.01" value="${r.pct||''}"><button class="btn danger" data-remove-line="${i}">×</button></div>`).join('');paintTotal();document.querySelectorAll('[data-line-center]').forEach(s=>s.onchange=()=>{rows[+s.dataset.lineCenter].center_id=s.value});document.querySelectorAll('[data-line-pct]').forEach(n=>n.oninput=()=>{rows[+n.dataset.linePct].pct=Number(n.value);paintTotal()});document.querySelectorAll('[data-remove-line]').forEach(b=>b.onclick=()=>{rows.splice(+b.dataset.removeLine,1);paint()})};
  paint();$('#showAllCenters')&&($('#showAllCenters').onchange=e=>{showAll=e.target.checked;paint()});$('#addLine').onclick=()=>{rows.push({center_id:'',pct:0});paint()};$('#saveAssignment').onclick=async()=>{const clean=rows.filter(r=>r.center_id&&r.pct>0),sum=clean.reduce((s,r)=>s+Number(r.pct),0);if(!clean.length||Math.abs(sum-100)>.001){$('#formError').textContent='La distribución debe sumar exactamente 100%.';return}if(new Set(clean.map(r=>r.center_id)).size!==clean.length){$('#formError').textContent='No repitas centros.';return}const off=clean.map(r=>center(r.center_id)).find(c=>c&&!c.active);if(off){$('#formError').textContent=`${off.name} está dado de baja: reemplazalo por otro centro.`;return}try{await run(sb.rpc('save_assignment',{p_person_id:id,p_valid_from:$('#assignmentDate').value,p_lines:clean}));$('#modal').close();await loadData();toast('Asignación guardada. Si cambió un porcentaje en un centro de otro responsable, deberá confirmarlo de nuevo.')}catch(e){$('#formError').textContent=e.message}}
}
function centerOptions(sel,rid,all){const opt=c=>`<option value="${c.id}" ${sel===c.id?'selected':''}>${esc(`${c.code} · ${c.name} · ${c.unit}${c.active?'':' · DADO DE BAJA'}`)}</option>`,avail=state.centers.filter(c=>c.active||c.id===sel),mine=avail.filter(c=>c.responsible_id&&c.responsible_id===rid),rest=avail.filter(c=>!mine.includes(c)&&(all||c.id===sel)),groups=new Map();rest.forEach(c=>{const k=c.responsible_id||'';groups.has(k)||groups.set(k,[]);groups.get(k).push(c)});const own=me?.role==='responsable'&&me.responsible_id===rid?'Mis centros':`Centros de ${responsible(rid)?.name||'su responsable'}`,other=[...groups].map(([k,cs])=>({label:k?`De ${responsible(k)?.name||'otro responsable'} · requiere su confirmación`:'Sin responsable asignado',cs})).sort((a,b)=>a.label.localeCompare(b.label,'es'));return`<option value="">Elegir centro</option>${mine.length?`<optgroup label="${esc(own)}">${mine.map(opt).join('')}</optgroup>`:''}${other.map(g=>`<optgroup label="${esc(g.label)}">${g.cs.map(opt).join('')}</optgroup>`).join('')}`}
function openDetail(id){modal(`Asignación de ${person(id).name}`,allocationHtml(id),`<button class="btn" data-close>Cerrar</button>`)}
async function confirmShared(key){const[personId,centerId]=key.split('|'),v=currentVersion(personId);try{await run(sb.from('shared_confirmations').upsert({period:monthDate(),person_id:personId,center_id:centerId,version_id:v.id,confirmed_by:session.user.email},{onConflict:'period,person_id,center_id'}));await audit('shared_confirmation',`Confirmación de ${person(personId).name} en ${center(centerId).name} para ${period}`);await loadData();toast('Dedicación confirmada.')}catch(e){toast(e.message,true)}}
async function saveCenterOwner(id,rid){try{await run(sb.from('centers').update({responsible_id:rid||null}).eq('id',id));await audit('center_owner',`Responsable actualizado para ${center(id).name}`);await loadData();toast('Responsable del centro actualizado.')}catch(e){toast(e.message,true)}}
function openNewCenter(){const units=[...new Set(state.centers.map(c=>c.unit))].sort();modal('Nuevo centro',`<label class="field">Código<input id="centerCode"></label><label class="field">Unidad<input id="centerUnit" list="centerUnits"><datalist id="centerUnits">${units.map(u=>`<option value="${esc(u)}">`).join('')}</datalist></label><label class="field">Centro<input id="centerName"></label><label class="field">Tipo<select id="centerType"><option value="">Elegir</option><option>Costo</option><option>Beneficio</option></select></label><div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveCenter">Guardar</button>`);$('#saveCenter').onclick=async()=>{const code=$('#centerCode').value.trim(),unit=$('#centerUnit').value.trim(),name=$('#centerName').value.trim(),type=$('#centerType').value;if(!code||!unit||!name||!type){$('#formError').textContent='Completá código, unidad, centro y tipo.';return}const dup=state.centers.find(c=>norm(c.code)===norm(code));if(dup){$('#formError').textContent=dup.active?`Ya existe el centro ${dup.name} con ese código.`:`Ese código es de ${dup.name}, que está dado de baja: usá Reactivar.`;return}try{await run(sb.from('centers').insert({id:code,code,unit,name,type,provisional:norm(code)==='prueba',active:true,sort_order:Math.max(0,...state.centers.map(c=>c.sort_order||0))+1}));await audit('center_create',`Alta de centro ${code} · ${name}`);$('#modal').close();await loadData();toast('Centro creado.')}catch(e){$('#formError').textContent=e.message}}}
function openCenterOff(id){const c=center(id),users=activePeople().filter(p=>allocation(p.id).some(a=>a.center_id===id));modal('Dar de baja centro',`<p><b>${esc(c.code)} · ${esc(c.name)}</b> · ${esc(c.unit)}</p><p>Desde ahora no se va a poder elegir en nuevas asignaciones. Las asignaciones y exportaciones de meses anteriores lo conservan.</p>${users.length?`<div class="notice danger"><b>${users.length} ${users.length===1?'persona lo tiene':'personas lo tienen'} en su asignación vigente:</b> ${users.map(p=>esc(p.name)).join(', ')}.<br>Van a quedar marcadas para reasignar.</div>`:''}`,`<button class="btn" data-close>Cancelar</button><button class="btn danger" id="confirmCenterOff">Dar de baja</button>`);$('#confirmCenterOff').onclick=async()=>{$('#modal').close();await setCenterActive(id,false)}}
async function setCenterActive(id,active){const c=center(id);try{await run(sb.from('centers').update({active}).eq('id',id));await audit(active?'center_reactivate':'center_deactivate',`${active?'Reactivación':'Baja'} de centro ${c.code} · ${c.name}`);await loadData();toast(active?'Centro reactivado.':'Centro dado de baja.')}catch(e){toast(e.message,true)}}
async function validateResponsible(){try{await run(sb.rpc('validate_responsible_month',{p_period:monthDate()}));await loadData();toast('Mes validado.')}catch(e){toast(e.message,true)}}
async function validateHr(){try{await run(sb.from('hr_validations').upsert({period:monthDate(),validated_by:session.user.email},{onConflict:'period'}));await audit('hr_validation',`RRHH validó la nómina ${period}`);await loadData();toast('Nómina mensual validada.')}catch(e){toast(e.message,true)}}

function openClearTest(){modal('Vaciar datos de prueba','<div class="notice danger"><b>Se eliminarán personas, responsables, asignaciones y validaciones.</b><br>El catálogo de centros, el administrador y los usuarios de RRHH se conservan. Usá esta opción sólo antes de la carga real.</div>',`<button class="btn" data-close>Cancelar</button><button class="btn danger" id="confirmClearTest">Vaciar datos</button>`);$('#confirmClearTest').onclick=async()=>{try{await run(sb.rpc('clear_operational_data'));$('#modal').close();await loadData();toast('Datos operativos eliminados. Ya podés importar la nómina real.')}catch(e){toast(e.message,true)}}}

function openNewResponsible(){
  modal('Nuevo responsable',`<label class="field">Nombre y apellido<input id="respName"></label><label class="field">Correo<input id="respEmail" type="email"></label>${initialPasswordField()}<div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveResponsible">Guardar</button>`);bindInitialPassword();
  $('#saveResponsible').onclick=async()=>{const name=$('#respName').value.trim(),email=$('#respEmail').value.trim().toLowerCase();if(!name||!email){$('#formError').textContent='Completá nombre y correo.';return}const pwd=readInitialPassword();if(!pwd)return;try{const data=await run(sb.from('responsibles').insert({name,email}).select().single());await run(sb.from('app_users').upsert({email,display_name:name,role:'responsable',responsible_id:data.id,active:true}));await run(sb.rpc('set_user_password',{target_email:email,new_password:pwd}));await audit('access',`Alta del responsable ${name}`);$('#modal').close();await loadData();toast('Responsable y acceso creados.')}catch(e){$('#formError').textContent=e.message}}
}
function openNewUser(){
  modal('Habilitar usuario',`<label class="field">Nombre<input id="userName"></label><label class="field">Correo<input id="userEmail" type="email"></label><label class="field">Perfil<select id="userRole"><option value="rrhh">RRHH</option>${me.role==='administrador'?'<option value="administrador">Administrador de costos</option>':''}</select></label>${initialPasswordField()}<div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="saveUser">Guardar</button>`);bindInitialPassword();
  $('#saveUser').onclick=async()=>{const row={display_name:$('#userName').value.trim(),email:$('#userEmail').value.trim().toLowerCase(),role:$('#userRole').value,active:true};if(!row.display_name||!row.email){$('#formError').textContent='Completá nombre y correo.';return}const pwd=readInitialPassword();if(!pwd)return;try{await run(sb.from('app_users').upsert(row));await run(sb.rpc('set_user_password',{target_email:row.email,new_password:pwd}));await audit('access',`Acceso ${row.role} habilitado para ${row.email}`);$('#modal').close();await loadData();toast('Usuario habilitado.')}catch(e){$('#formError').textContent=e.message}}
}

function openImport(){
  modal('Importación inicial',`<div class="drop"><strong>Seleccioná la plantilla completa</strong><span>Debe contener las hojas “Nomina” y “Responsables”. Sólo está habilitado cuando la nómina está vacía.</span><label class="btn primary" for="rosterFile">Elegir Excel</label><input id="rosterFile" type="file" accept=".xlsx"></div><div id="importPreview"></div><div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="confirmImport" disabled>Importar nómina</button>`);
  let parsed;$('#rosterFile').onchange=async e=>{try{parsed=await parseRosterXlsx(await e.target.files[0].arrayBuffer());$('#importPreview').innerHTML=`<div class="notice" style="margin-top:15px"><b>${parsed.people.length} personas y ${parsed.responsibles.length} responsables.</b></div>`;$('#confirmImport').disabled=false}catch(err){$('#formError').textContent=err.message}};
  $('#confirmImport').onclick=async()=>{try{const respRows=await run(sb.from('responsibles').upsert(parsed.responsibles,{onConflict:'email'}).select());const byName=new Map(respRows.map(r=>[norm(r.name),r]));for(const r of respRows)await run(sb.from('app_users').upsert({email:r.email,display_name:r.name,role:'responsable',responsible_id:r.id,active:true}));const people=parsed.people.map(p=>({...p,responsible_id:byName.get(norm(p.responsible_name))?.id}));if(people.some(p=>!p.responsible_id))throw new Error('Hay responsables de la nómina que no aparecen en la hoja Responsables.');await run(sb.from('people').insert(people.map(({responsible_name,...p})=>p)));for(const p of people)await run(sb.from('responsible_history').insert({person_id:p.id,valid_from:p.start_date,responsible_id:p.responsible_id,created_by:session.user.email}));await audit('initial_import',`Importación inicial: ${people.length} personas`);$('#modal').close();await loadData();toast('Importación inicial completada.')}catch(err){$('#formError').textContent=err.message}}
}

function openImportCenters(){
  modal('Importar centros',`<div class="drop"><strong>Seleccioná el Excel de centros de DMO</strong><span>La hoja debe incluir Código, Unidad, Centro y Tipo. Tipo debe indicar Costo o Beneficio.</span><label class="btn primary" for="centersFile">Elegir Excel</label><input id="centersFile" type="file" accept=".xlsx"></div><div id="centersPreview"></div><div id="formError" class="error"></div>`,`<button class="btn" data-close>Cancelar</button><button class="btn primary" id="confirmCenters" disabled>Importar centros</button>`);
  let rows;$('#centersFile').onchange=async e=>{try{rows=await parseCentersXlsx(await e.target.files[0].arrayBuffer());$('#centersPreview').innerHTML=`<div class="notice" style="margin-top:15px"><b>${rows.length} centros encontrados.</b><br>Los códigos existentes se actualizarán.</div>`;$('#confirmCenters').disabled=false}catch(err){$('#formError').textContent=err.message}};
  $('#confirmCenters').onclick=async()=>{try{await run(sb.from('centers').upsert(rows,{onConflict:'id'}));await audit('centers_import',`Importación de catálogo: ${rows.length} centros`);$('#modal').close();await loadData();toast('Catálogo de centros actualizado.')}catch(err){$('#formError').textContent=err.message}}
}

async function parseCentersXlsx(buffer){
  const book=await readWorkbook(buffer);for(const sheetRows of book.values()){const hi=sheetRows.findIndex(r=>{const h=r.map(norm);return h.some(x=>['codigo','codigocentro','codigocentrocosto'].includes(x))&&h.some(x=>['centro','nombre','nombrecentro','centrodecostos','centrodecosto'].includes(x))&&h.includes('tipo')});if(hi<0)continue;const h=headerMap(sheetRows[hi]),idx=names=>names.map(n=>h[norm(n)]).find(i=>i!==undefined),codeIdx=idx(['codigo','codigo_centro','codigo_centro_costo']),unitIdx=idx(['unidad','sede']),nameIdx=idx(['centro','nombre','nombre_centro','centro_de_costos','centro_de_costo']),typeIdx=idx(['tipo']);const rows=sheetRows.slice(hi+1).filter(r=>String(r[codeIdx]??'').trim()).map((r,i)=>{const code=String(r[codeIdx]).trim(),rawType=norm(r[typeIdx]),type=rawType.includes('beneficio')?'Beneficio':rawType.includes('costo')?'Costo':'';if(!type)throw new Error(`Tipo inválido en la fila ${hi+i+2}. Debe ser Costo o Beneficio.`);return{id:code,code,unit:String(r[unitIdx]??'').trim()||'Sin unidad',name:String(r[nameIdx]??'').trim(),type,provisional:norm(code)==='prueba',active:true,sort_order:i+1}});if(rows.some(r=>!r.name))throw new Error('Hay centros sin nombre.');if(new Set(rows.map(r=>norm(r.code))).size!==rows.length)throw new Error('Hay códigos de centro repetidos.');return rows}throw new Error('No se encontró una hoja con las columnas Código, Centro y Tipo.')
}

async function parseRosterXlsx(buffer){
  const book=await readWorkbook(buffer),nom=book.get('nomina'),res=book.get('responsables');if(!nom||!res)throw new Error('El archivo debe tener las hojas Nomina y Responsables.');
  const ni=nom.findIndex(r=>r.map(norm).includes('legajo')&&r.map(norm).includes('responsableprincipal')),ri=res.findIndex(r=>r.map(norm).includes('responsableprincipal')&&r.map(norm).includes('correoresponsable'));if(ni<0||ri<0)throw new Error('No se encontraron los encabezados esperados en la plantilla.');
  const rh=headerMap(res[ri]),nh=headerMap(nom[ni]);
  const responsibles=res.slice(ri+1).filter(r=>r.some(Boolean)).map(r=>({name:cell(r,rh,'responsable_principal'),email:cell(r,rh,'correo_responsable').toLowerCase(),active:true}));
  const people=nom.slice(ni+1).filter(r=>r.some(Boolean)).map(r=>({id:cell(r,nh,'legajo'),name:cell(r,nh,'nombre'),responsible_name:cell(r,nh,'responsable_principal'),start_date:excelDate(cell(r,nh,'fecha_alta'))||'2025-01-01',end_date:excelDate(cell(r,nh,'fecha_baja'))||null,active:true}));
  if(responsibles.some(r=>!r.name||!r.email)||people.some(p=>!p.id||!p.name||!p.responsible_name))throw new Error('Hay filas incompletas en la plantilla.');if(new Set(people.map(p=>norm(p.id))).size!==people.length)throw new Error('Hay legajos repetidos.');return{responsibles,people}
}
const headerMap=row=>Object.fromEntries((row||[]).map((v,i)=>[norm(v),i]));
const cell=(row,map,name)=>String(row[map[norm(name)]]??'').trim();
function excelDate(v){if(!v)return'';if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;if(/^\d+(\.\d+)?$/.test(v)){const d=new Date(Date.UTC(1899,11,30)+Number(v)*86400000);return d.toISOString().slice(0,10)}const p=String(v).split('/');if(p.length===3)return`${p[2]}-${p[1].padStart(2,'0')}-${p[0].padStart(2,'0')}`;return''}
async function readWorkbook(buffer){
  const zip=await JSZip.loadAsync(buffer),parser=new DOMParser(),wb=parser.parseFromString(await zip.file('xl/workbook.xml').async('string'),'application/xml'),rels=parser.parseFromString(await zip.file('xl/_rels/workbook.xml.rels').async('string'),'application/xml'),shared=[];
  const sf=zip.file('xl/sharedStrings.xml');if(sf){const sx=parser.parseFromString(await sf.async('string'),'application/xml');[...sx.getElementsByTagName('si')].forEach(si=>shared.push([...si.getElementsByTagName('t')].map(t=>t.textContent).join('')))}
  const out=new Map();for(const sh of [...wb.getElementsByTagName('sheet')]){const rel=[...rels.getElementsByTagName('Relationship')].find(x=>x.getAttribute('Id')===sh.getAttribute('r:id'));let target=rel.getAttribute('Target').replace(/^\//,'');if(!target.startsWith('xl/'))target='xl/'+target.replace(/^\.\//,'');const xml=parser.parseFromString(await zip.file(target).async('string'),'application/xml'),rows=[];for(const rr of [...xml.getElementsByTagName('row')]){const row=[];for(const c of [...rr.getElementsByTagName('c')]){const letters=((c.getAttribute('r')||'A1').match(/[A-Z]+/)||['A'])[0];let col=0;for(const ch of letters)col=col*26+ch.charCodeAt(0)-64;col--;const t=c.getAttribute('t'),raw=c.getElementsByTagName('v')[0]?.textContent||'';row[col]=t==='inlineStr'?[...c.getElementsByTagName('t')].map(x=>x.textContent).join(''):t==='s'?shared[Number(raw)]??'':raw}rows.push(row)}out.set(norm(sh.getAttribute('name')),rows)}return out
}

async function downloadOutput(){const people=activePeople(),alloc=new Map(people.map(p=>[p.id,allocation(p.id)])),used=new Set([...alloc.values()].flat().map(a=>a.center_id)),cols=state.centers.filter(c=>c.active||used.has(c.id)),fixed=5,first=fixed+1,last=fixed+cols.length,L=colName,excelDate=d=>d?{v:(Date.UTC(...d.split('-').map((x,i)=>i===1?x-1:+x))-Date.UTC(1899,11,30))/86400000,s:7}:'',legajo=id=>/^[1-9]\d{0,14}$/.test(String(id))?Number(id):String(id);
  const title=`Asignación de personal DMO · ${periodLabel().replace(/^./,c=>c.toUpperCase())}`,n=people.length,top=5,bottom=Math.max(top,top+n-1),matrix=[[{v:title,s:3}],[{v:'Faltan asignar:',s:5},{f:`COUNTIF(${L(last+2)}${top}:${L(last+2)}${bottom},"Falta")`,v:0,s:5}],[...Array(fixed-1).fill(''),{v:'Código centro',s:4},...cols.map(c=>({v:String(c.code),s:4}))],[...['Legajo','Apellido y nombres','Responsable','Fecha ingreso','Fecha baja'],...cols.map(c=>c.name),'Total','Estado'].map(v=>({v,s:1}))];
  people.forEach((p,i)=>{const r=top+i,pct=new Map();alloc.get(p.id).forEach(a=>pct.set(a.center_id,Math.round(((pct.get(a.center_id)||0)+Number(a.pct)/100)*1e6)/1e6));const total=[...pct.values()].reduce((s,x)=>s+x,0),ok=Math.abs(total-1)<1e-6;matrix.push([legajo(p.id),p.name,responsible(p.responsible_id)?.name||'',excelDate(p.start_date),excelDate(p.end_date),...cols.map(c=>({v:pct.get(c.id)||0,s:2})),{f:`SUM(${L(first)}${r}:${L(last)}${r})`,v:total,s:6},{f:`IF(ROUND(${L(last+1)}${r},4)<>1,"Falta","Ok")`,v:ok?'Ok':'Falta',t:'str',s:8}]);if(!ok)matrix[1][1].v++});
  const detail=[['Periodo','Legajo','Nombre','Fecha alta','Fecha baja','Responsable principal','Código centro','Unidad','Centro','Tipo','Porcentaje']];people.forEach(p=>alloc.get(p.id).forEach(a=>{const c=center(a.center_id);detail.push([period,p.id,p.name,p.start_date,p.end_date||'',responsible(p.responsible_id)?.name||'',c.code,c.unit,c.name,c.type,{v:Math.round(Number(a.pct)*1e4)/1e6,s:2}])}));detail[0]=detail[0].map(v=>({v,s:1}));
  const blob=await makeXlsx([{name:'Asignación',rows:matrix,widths:[10,32,24,12,12,...cols.map(()=>14),10,9],freeze:[fixed,4],filter:`A4:${L(last+2)}${bottom}`,heights:{4:48}},{name:'Detalle',rows:detail,widths:[10,10,32,12,12,24,14,12,28,12,12],freeze:[0,1],filter:`A1:K${detail.length}`}]);downloadBlob(blob,`DMO_Asignaciones_${period}.xlsx`);await audit('export',`Exportación mensual ${period}: ${n} personas, ${detail.length-1} asignaciones`);toast('Excel generado.')}
function xmlEsc(v){return String(v??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]))}
function colName(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
async function makeXlsx(sheets){
  const zip=new JSZip(),ct='application/vnd.openxmlformats-officedocument.spreadsheetml',rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
  zip.file('[Content_Types].xml',`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="${ct}.sheet.main+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="${ct}.worksheet+xml"/>`).join('')}<Override PartName="/xl/styles.xml" ContentType="${ct}.styles+xml"/></Types>`);
  zip.folder('_rels').file('.rels',`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${rel}/officeDocument" Target="xl/workbook.xml"/></Relationships>`);
  zip.folder('xl').file('workbook.xml',`<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="${rel}"><sheets>${sheets.map((s,i)=>`<sheet name="${xmlEsc(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`);
  zip.folder('xl').folder('_rels').file('workbook.xml.rels',`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="${rel}/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="${rel}/styles" Target="styles.xml"/></Relationships>`);
  zip.folder('xl').file('styles.xml','<?xml version="1.0"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="0.00%;-0.00%;&quot;-&quot;"/></numFmts><fonts count="5"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font><font><b/><sz val="14"/><color rgb="FF14282B"/><name val="Calibri"/></font><font><sz val="9"/><color rgb="FF7A8587"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF007E76"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="9"><xf/><xf fontId="1" fillId="2" applyFont="1" applyFill="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="164" applyNumberFormat="1"/><xf fontId="2" applyFont="1"/><xf fontId="3" applyFont="1" applyAlignment="1"><alignment horizontal="center"/></xf><xf fontId="4" applyFont="1"/><xf numFmtId="164" fontId="4" applyNumberFormat="1" applyFont="1"/><xf numFmtId="14" applyNumberFormat="1"/><xf applyAlignment="1"><alignment horizontal="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>');
  const cell=(x,ref)=>{if(x===''||x==null)return'';const o=typeof x==='object'?x:{v:x},s=o.s?` s="${o.s}"`:'';if(o.f)return`<c r="${ref}"${s}${o.t?` t="${o.t}"`:''}><f>${xmlEsc(o.f)}</f><v>${xmlEsc(o.v)}</v></c>`;return typeof o.v==='number'?`<c r="${ref}"${s}><v>${o.v}</v></c>`:`<c r="${ref}" t="inlineStr"${s}><is><t>${xmlEsc(o.v)}</t></is></c>`};
  sheets.forEach((sh,i)=>{const[x,y]=sh.freeze||[0,0],pane=x||y?`<pane${x?` xSplit="${x}"`:''}${y?` ySplit="${y}"`:''} topLeftCell="${colName(x+1)}${y+1}" activePane="${x&&y?'bottomRight':y?'bottomLeft':'topRight'}" state="frozen"/>`:'',cols=sh.widths?`<cols>${sh.widths.map((w,ci)=>`<col min="${ci+1}" max="${ci+1}" width="${w}" customWidth="1"/>`).join('')}</cols>`:'',data=sh.rows.map((r,ri)=>`<row r="${ri+1}"${sh.heights?.[ri+1]?` ht="${sh.heights[ri+1]}" customHeight="1"`:''}>${r.map((v,ci)=>cell(v,colName(ci+1)+(ri+1))).join('')}</row>`).join('');zip.folder('xl').folder('worksheets').file(`sheet${i+1}.xml`,`<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"${i===0?' tabSelected="1"':''}>${pane}</sheetView></sheetViews><sheetFormatPr defaultRowHeight="15"/>${cols}<sheetData>${data}</sheetData>${sh.filter?`<autoFilter ref="${sh.filter}"/>`:''}</worksheet>`)});
  return zip.generateAsync({type:'blob',mimeType:`${ct}.sheet`})
}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

boot().catch(e=>showLoginError(e.message));
